version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rede

  qualidade_agua:
    image: qualidade_agua
    container_name: qualidade_agua
    ports:
      - "8000:8000"  # Porta 8000 exposta para acessar as métricas
    networks:
      - rede

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - rede

networks:
  rede:
    driver: bridge
